# Generated by Django 4.1.5 on 2023-01-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=10, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
